### ISSUE TITLE
Section 5: submit TestFest repo as the final section that teaches how to pass tests.

### ISSUE THREAD

**Issue by akanshmurthy** [akanshmurthy/docs#5]
We can also have them write new tests if needed in the same repo.

**Comment by akanshmurthy** [comment]
We'll need to incorporate the latest testathon repo (since people added fixes to some tests) and the one with all the broken tests that was sent out the day of the testfest workshop for this issue. cc: @schaui6

**Comment by akanshmurthy** [comment]
Any thoughts on this? @schaui6

**Comment by schaui6** [comment]
@akanshmurthy we could write a tutorial on how to approach the test to fix it, like a written walk through guide for beginners and more advanced students could just work just like they did at the workshop, we'll just need to provide a link to the repos. Basically advance students would have less hand holding.

**Comment by akanshmurthy** [comment]
I mean more that the Github repo doesn't have all the additional tests that were part of the repo that was used during the workshop. The Github repo and the one we used need to be fused, no?

**Comment by schaui6** [comment]
ah..I see your point.  We would need to create a repo under railsbridge
