### ISSUE TITLE
Help us incorporate this testing curriculum :)

### ISSUE THREAD

**Issue by schaui6** [akanshmurthy/docs#6]
@akanshmurthy @tigarcia @siruguri  @IanThorp @camachom @eyeyellow @haseebq

Feel free to tag others if there is any interest in working on this project. Thanks!

https://github.com/akanshmurthy/railsbridge-testathon

**Comment by akanshmurthy** [comment]
I've created the initial branch (testing-curriculum) and set up the files so feel free to start claiming issues and contributing. Just add your commits to the same branch (if we claim different issues, there shouldn't be merge conflicts).

https://github.com/akanshmurthy/docs/pull/7/commits

We want to try and incorporate some of this: https://github.com/railsbridge/docs/issues/586.

**Comment by akanshmurthy** [comment]
All sections have been assigned; thanks for playing!
